api/urls.py
"""API Urls"""
# pylint: disable=invalid-name
from django.conf.urls import url, include
from rest_framework import routers

from api.views import DistrictViewSet


router = routers.DefaultRouter()
router.register(r'districts', DistrictViewSet, base_name='districts')


urlpatterns = [
    url(r'^', include(router.urls)),
]

blocks/models.py
"""Models for the block functionality"""
from django.db import models

from branding.mixins import OrganizationMixin
from rendering.validators import validate_template
from everyvoter_common.utils.models import TimestampModel, UUIDModel
from everyvoter_common.utils.soft_delete import SoftDeleteModel, ActiveManager


class BlockManager(ActiveManager):
    """Manager for blocks"""
    def get_queryset(self):
        queryset = super(BlockManager, self).get_queryset()
        queryset = queryset.exclude(geodataset__deleted=True)
        return queryset



class Block(SoftDeleteModel, TimestampModel, UUIDModel, OrganizationMixin):
    """Block of content"""
    name = models.CharField('Block Name', max_length=50)
    code = models.TextField('HTML Code', validators=[validate_template])
    categories = models.ManyToManyField(
        'blocks.BlockCategory', blank=True)
    weight = models.IntegerField('Weight', default=50)
    geodataset = models.ForeignKey('geodataset.GeoDataset')

    objects = BlockManager()

    class Meta(object):
        """Meta options for BLock"""
        verbose_name = "Block"
        verbose_name_plural = "Blocks"

    def __unicode__(self):
        """Unicode representation of the block"""
        return self.name


class BlockCategory(TimestampModel, UUIDModel, OrganizationMixin):
    """Category used for blocks"""
    name = models.CharField('Blog Category Name', max_length=50)

    class Meta(object):
        """Meta options for Blog Tag"""
        verbose_name = "Block Category"
        verbose_name_plural = "Block Categories"

    def __unicode__(self):
        """Unicode representation of the block"""
        return self.name

geodataset/models.py
"""Models for Geodataset"""
from django.db import models
from django.utils.functional import cached_property

from branding.mixins import OrganizationMixin
from everyvoter_common.utils.models import TimestampModel, UUIDModel
from everyvoter_common.utils.soft_delete import SoftDeleteModel, ActiveManager


class GeoDataset(SoftDeleteModel, TimestampModel, UUIDModel, OrganizationMixin):
    """Dataset that contains blocks, targets, and data"""
    name = models.CharField('Name', max_length=50)
    categories = models.ManyToManyField(
        'geodataset.GeoDatasetCategory', blank=True)

    objects = ActiveManager()

    class Meta(object):
        """Meta options for Geodataset model"""
        verbose_name = "GeoDataset"
        verbose_name_plural = "GeoDatasets"

    def __unicode__(self):
        """String representation of model"""
        return self.name


class Entry(TimestampModel, UUIDModel):
    """Entry of data in a geodataset"""
    geodataset = models.ForeignKey(GeoDataset)
    district = models.ForeignKey('election.LegislativeDistrict')
    fields = models.ManyToManyField(
        'geodataset.Field', through='geodataset.FieldValue', blank=True)

    class Meta(object):
        """Meta options for GeoDatasetRow model"""
        verbose_name = "Geo Dataset Entry"
        verbose_name_plural = "Geo Dataset Entry"

    def __unicode__(self):
        """Unicode representation of the entry"""
        return u'{geodataset} {district}'.format(
            geodataset=self.geodataset.name, district=self.district.ocd_id)

    @cached_property
    def data(self):
        """Data for the entry in dictionary format"""
        return dict(self.fields.values_list(
            'name', 'fieldvalue__value'))



class Field(TimestampModel, UUIDModel):
    """Field in a geodataset"""
    name = models.CharField('Name', max_length=255)
    geodataset = models.ForeignKey(GeoDataset)

    class Meta(object):
        """Meta options for Field model"""
        verbose_name = "Field"
        verbose_name_plural = "Fields"

    def __unicode__(self):
        """Unicode representation of the field"""
        return self.name


class FieldValue(TimestampModel, UUIDModel):
    """Value of a field in an entry of a geodataset"""
    field = models.ForeignKey(Field)
    entry = models.ForeignKey(Entry)
    value = models.TextField()


class GeoDatasetCategory(TimestampModel, UUIDModel, OrganizationMixin):
    """Category used for GeoDatasets"""
    name = models.CharField('GeoDataset Category Name', max_length=50)

    class Meta(object):
        """Meta options for Blog Tag"""
        verbose_name = "GeoDataset Category"
        verbose_name_plural = "GeoDataset Categories"

    def __unicode__(self):
        """Unicode representation of the category"""
        return self.name

geodataset/forms.py
"""Forms for account app"""
from django import forms

from geodataset.models import GeoDataset
from geodataset.validators import validate_geodataset_upload


class GeoDatasetUploadForm(forms.ModelForm):
    """Upload a geodataset"""
    file = forms.FileField(validators=[validate_geodataset_upload])

    class Meta(object):
        """Meta options for form"""
        model = GeoDataset
        fields = ['name', 'categories', 'file']

geodataset/views.py
"""Views for geodataset"""
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponse
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    CreateView, DetailView, UpdateView, ListView, DeleteView
)
from django_filters.views import FilterView
import unicodecsv

from branding.mixins import OrganizationViewMixin, OrganizationCreateViewMixin
from everyvoter_common.utils.soft_delete import SoftDeleteView
from everyvoter_common.utils.slug import slugify_header
from manage.mixins import ManageViewMixin
from geodataset.forms import GeoDatasetUploadForm
from geodataset.models import GeoDataset, GeoDatasetCategory, Entry, FieldValue
from geodataset.utils import (
    process_geodataset_file, generate_csv_data
)
from geodataset.filters import GeoDatasetFilter


class GeoDatasetListView(OrganizationViewMixin, ManageViewMixin, FilterView):
    """List of all GeoDatasets"""
    model = GeoDataset
    paginate_by = 10
    context_object_name = 'geodatasets'
    filterset_class = GeoDatasetFilter
    template_name_suffix = '_list'

    def get_context_data(self, *args, **kwargs):
        """Get the context for the page"""
        response = super(GeoDatasetListView, self).get_context_data(
            *args, **kwargs)

        # Only allow filtering of categories contained in its own organization
        response['filter'].filters['categories'].queryset = response[
            'filter'].filters['categories'].queryset.filter(
                organization=self.request.organization)

        return response


class CommonGeoDatasetEditView(OrganizationViewMixin, ManageViewMixin,
                               OrganizationCreateViewMixin, CreateView):
    """Create or edit a geodataset"""
    model = GeoDataset
    form_class = GeoDatasetUploadForm
    success_url = reverse_lazy('manage:dataset:list_geodatasets')

    def get_form(self):
        """Get the form"""
        form = super(CommonGeoDatasetEditView, self).get_form()

        # pylint: disable=line-too-long
        form.fields['categories'].queryset = form.fields['categories'].queryset.filter(
            organization=self.request.organization)

        return form


    def form_valid(self, form):
        """Handle a valid form"""

        if form.instance.pk:
            created = False
        else:
            created = True

        # Assign an organization and save the geodataset itself
        response = super(CommonGeoDatasetEditView, self).form_valid(form)

        if form.cleaned_data['file']:
            process_geodataset_file(
                form.cleaned_data['file'], self.object, created)

        return response


class GeoDatasetCreateView(CommonGeoDatasetEditView, CreateView):
    """Create a Geodataset"""


class GeoDatasetUpdateView(CommonGeoDatasetEditView, UpdateView):
    """Update a Geodataset"""
    slug_field = 'uuid'
    context_object_name = 'geodataset'

    def get_form(self):
        """Get the form"""
        form = super(GeoDatasetUpdateView, self).get_form()

        form.fields['file'].required = False

        return form


class GeoDatasetDetailView(OrganizationViewMixin, ManageViewMixin, DetailView):
    """Detail view for an individual GeoDataset"""
    model = GeoDataset
    slug_field = 'uuid'
    context_object_name = 'geodataset'


    def get_context_data(self, *args, **kwargs):
        """Get the context for the view"""
        context = super(GeoDatasetDetailView, self).get_context_data(
            *args, **kwargs)

        context['entries'] = self.object.entry_set.select_related(
            ).order_by('district__ocd_id')

        return context


class GeoDatasetDeleteView(OrganizationViewMixin, ManageViewMixin,
                           SoftDeleteView):
    """Delete a geodataset"""
    model = GeoDataset
    slug_field = 'uuid'
    context_object_name = 'geodataset'
    success_url = reverse_lazy('manage:dataset:list_geodatasets')


class GeoDatasetCSVView(OrganizationViewMixin, ManageViewMixin, DetailView):
    """Download a CSV of an individual GeoDataset"""
    model = GeoDataset
    slug_field = 'uuid'

    def render_to_response(self, context, **response_kwargs):
        """Render to response"""
        response = HttpResponse(content_type='text/csv')
        # pylint: disable=line-too-long
        response['Content-Disposition'] = 'attachment; filename="{}.csv"'.format(
            slugify_header(self.object.name))

        data, field_names = generate_csv_data(self.object)

        writer = unicodecsv.DictWriter(response, fieldnames=field_names)
        writer.writeheader()
        for row in data:
            writer.writerow(row)

        return response


class EntryDetailView(ManageViewMixin, DetailView):
    """Detail view of an entry"""
    model = Entry
    slug_field = 'uuid'
    queryset = Entry.objects.select_related('district', 'geodataset')
    context_object_name = 'entry'

    def get_queryset(self):
        """Get the queryset filtered by organization"""
        queryset = super(EntryDetailView, self).get_queryset()
        return queryset.filter(
            geodataset__organization=self.request.organization)


class FieldValueUpdateView(ManageViewMixin, UpdateView):
    """Update a FieldValue"""
    model = FieldValue
    slug_field = 'uuid'
    fields = ['value']
    context_object_name = 'fieldvalue'
    queryset = FieldValue.objects.select_related(
        'entry', 'field', 'entry__geodataset', 'entry__district')

    def get_queryset(self):
        """Get the queryset filtered by organization"""
        queryset = super(FieldValueUpdateView, self).get_queryset()
        return queryset.filter(
            entry__geodataset__organization=self.request.organization)

    def get_success_url(self):
        """Get the URL to redirect to on a successful update"""
        return reverse('manage:dataset:view_entry',
                       kwargs={'slug': self.object.entry.uuid})


class GeoDatasetCategoryListView(OrganizationViewMixin, ManageViewMixin,
                                 ListView):
    """List all geodataset categories"""
    model = GeoDatasetCategory
    paginate_by = 10
    context_object_name = 'geodatasetcategories'


class GeoDatasetCategoryCreateView(ManageViewMixin, SuccessMessageMixin,
                                   OrganizationCreateViewMixin, CreateView):
    """Create a geodataset category"""
    model = GeoDatasetCategory
    fields = ['name']
    success_url = reverse_lazy('manage:dataset:list_geodatasetcategories')
    success_message = "Dataset Category %(name)s was created"


class GeoDatasetCategoryUpdateView(ManageViewMixin, SuccessMessageMixin,
                                   OrganizationViewMixin, UpdateView):
    """Edit a geodataset category"""
    model = GeoDatasetCategory
    slug_field = 'uuid'
    fields = ['name']
    context_object_name = 'geodatasetcategory'
    success_url = reverse_lazy('manage:dataset:list_geodatasetcategories')
    success_message = "Dataset Category %(name)s was edited"


class GeoDatasetCategoryDeleteView(ManageViewMixin, SuccessMessageMixin,
                                   OrganizationViewMixin, DeleteView):
    """Delete a geodataset category"""
    model = GeoDatasetCategory
    slug_field = 'uuid'
    context_object_name = 'geodatasetcategory'
    success_url = reverse_lazy('manage:dataset:list_geodatasetcategories')
    success_message = "Dataset Category %(name)s was deleted"

geodataset/templates/geodataset/entry_detail.html
{% extends "manage/manage_base.html" %}
{% load sekizai_tags crispy_forms_tags %}

{% block title %}{{ entry.geodataset.name }}{% endblock title %}

{% block content %}
{% add_data "body-class" "election" %}



<div class="content-wrapper">



    <div class="col-md-12">
        <div class="row">

            <div class="col-md-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'manage:dataset:view_geodataset' entry.geodataset.uuid %}">{{ entry.geodataset }}</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{{ entry.district }} ({{ entry.district.ocd_id }})</li>
                    </ol>
                </nav>

                <div class="card">
                    <div class="card-header">{{ entry.district }} Values</div>
                    <div class="table-responsive-lg">
                      <table class="table">
                        <thead>
                            <tr>
                                <th>Field Name</th>
                                <th>Value</th>
                                <th>Update</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for fieldvalue in entry.fieldvalue_set.all %}
                            <tr>
                                <td scope="row">{{ fieldvalue.field }}</td>
                                <td scope="row">{{ fieldvalue.value }}</td>
                                <td scope="row"><a href="{% url 'manage:dataset:update_fieldvalue' fieldvalue.uuid %}">Update</a></td>
                            </tr>
                        {% endfor %}

                        </tbody>
                      </table>
                    </div>
                </div>

            </div>


        </div>
    </div>
</div>

{% endblock %}

geodataset/templates/geodataset/fieldvalue_form.html
{% extends "manage/manage_base.html" %}
{% load sekizai_tags crispy_forms_tags %}

{% block title %}Edit Field {{ fieldvalue.field }}{% endblock title %}

{% block content %}
{% add_data "body-class" "election" %}
{% add_data "body-class" "form-page" %}
<div class="content-wrapper">
    <div class="col-lg-12">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'manage:dataset:view_geodataset' fieldvalue.entry.geodataset.uuid %}">{{ fieldvalue.entry.geodataset }}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'manage:dataset:view_entry' fieldvalue.entry.uuid %}">{{ fieldvalue.entry.district }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ fieldvalue.field }}</li>
        </ol>
    </nav>

    <div class="card">
        <div class="card-header">Edit Field {{ fieldvalue.field }} on {{ fieldvalue.entry }}</div><div class="card-body">

            <form role="form" method="POST" action="" enctype="multipart/form-data">
            {{ form|crispy }}
            <button type="submit" class="btn btn-block btn-primary">Save</button>
            {% csrf_token %}
            </form>
</div></div></div></div>
    </div>
{% endblock %}

geodataset/templates/geodataset/geodataset_confirm_delete.html
{% extends "manage/manage_base.html" %}
{% load sekizai_tags crispy_forms_tags %}

{% block title %}Delete {{ geodataset.name }}{% endblock title %}

{% block content %}
{% add_data "body-class" "targets" %}

<div class="content-wrapper">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Delete {{ geodataset.name }}</div>
            <div class="card-body">
                <form role="form" method="POST" action="">
                    <p>Are you sure you want to delete <strong>{{ geodataset.name }}</strong>? You cannot undo this.</p>
                    <p><strong>Deleting datasets also deletes all their blocks.</strong></p>
                <button type="submit" class="btn btn-danger">Delete</button>
                {% csrf_token %}
                </form>
            </div>
        </div>

    </div>
</div>

{% endblock %}

geodataset/templates/geodataset/geodataset_detail.html
{% extends "manage/manage_base.html" %}
{% load sekizai_tags crispy_forms_tags %}

{% block title %}{{ geodataset.name }}{% endblock title %}

{% block content %}
{% add_data "body-class" "election" %}
<div class="content-wrapper">
    <div class="col-md-12">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">{{ geodataset }}</li>
            </ol>
        </nav>

        <div class="row">

            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ geodataset.name }} Blocks</div>
                    <div class="table-responsive-lg">
                      <table class="table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Preview</th>
                                <th>Update</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for content_block in geodataset.block_set.all %}
                            <tr>
                                <td scope="row">{{ content_block.name }}</td>
                                <td scope="row"><a href="{% url 'manage:blocks:preview_block' content_block.uuid %}">Preview</a></td>
                                <td scope="row"><a href="{% url 'manage:blocks:update_block' content_block.uuid %}">Update</a></td>
                                <td scope="row"><a href="{% url 'manage:blocks:delete_block' content_block.uuid %}">Delete</a></td>
                            </tr>
                        {% endfor %}

                        </tbody>
                      </table>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">Districts</div>
                    <div class="table-responsive-lg">
                      <table class="table">
                        <thead>
                            <tr>
                                <th>District Name</th>
                                <th>OCD ID</th>
                                <th>View</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for entry in entries %}
                            <tr>
                                <td scope="row">{{ entry.district }}</td>
                                <td scope="row">{{ entry.district.ocd_id }}</td>
                                <td scope="row"><a href="{% url 'manage:dataset:view_entry' entry.uuid %}">View</a></td>
                            </tr>
                        {% endfor %}

                        </tbody>
                      </table>
                    </div>
                </div>

            </div>

            <div class="col-md-4">
                <a href="{% url 'manage:dataset:update_geodataset' geodataset.uuid %}" class="btn btn-block btn-primary btn-lg btn-card">Update</a>

                <a href="{% url 'manage:dataset:download_geodataset' geodataset.uuid %}" class="btn btn-block btn-primary btn-lg btn-card">Download</a>

                <div class="card">
                    <div class="card-header">Fields</div>
                    <div class="table-responsive-lg">
                      <table class="table">
                        <thead>
                            <tr>
                                <th>Name</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for field in geodataset.field_set.all %}
                            <tr>
                                <td scope="row">{{ field.name }}</td>
                            </tr>
                        {% endfor %}

                        </tbody>
                      </table>
                    </div>
                </div>

                <a href="{% url 'manage:dataset:delete_geodataset' geodataset.uuid %}" class="btn btn-block btn-danger btn-lg btn-card">Delete</a>

            </div>

        </div>
    </div>
</div>

{% endblock %}

geodataset/templates/geodataset/geodataset_form.html
{% extends "manage/manage_base.html" %}
{% load sekizai_tags crispy_forms_tags %}

{% block title %}{% if geodataset %}Edit Geo Dataset {{ geodataset.name }}{% else %}Create Geo Dataset{% endif %}{% endblock title %}

{% block content %}
{% add_data "body-class" "election" %}
{% add_data "body-class" "form-page" %}
<div class="content-wrapper">
    <div class="col-lg-12">

    {% if geodataset %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'manage:dataset:view_geodataset' geodataset.uuid %}">{{ geodataset }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Update</li>
        </ol>
    </nav>
    {% endif %}


    <div class="card">
        <div class="card-header">{% if geodataset %}Update Geo Dataset {{ geodataset.name }}{% else %}Create Geo Dataset{% endif %}</div><div class="card-body">

            <form role="form" method="POST" action="" enctype="multipart/form-data">
            {{ form|crispy }}
            <button type="submit" class="btn btn-block btn-primary">Save</button>
            {% csrf_token %}
            </form>
</div></div></div></div>
    </div>
{% endblock %}

geodataset/templates/geodataset/geodataset_list.html
{% extends "manage/manage_base.html" %}
{% load sekizai_tags crispy_forms_tags %}

{% block title %}{{ organization.platform_name }} Datasets{% endblock title %}

{% block content %}
{% add_data "body-class" "election" %}
<div class="content-wrapper">

    <div class="col-md-12">
        <div class="row">
            <div class="col-md-9">
                <div class="card">
                  <!-- Default card contents -->
                  <div class="card-header">Existing Datasets</div>
                  <!-- Table -->
                  <div class="table-responsive-lg">
                  <table class="table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Update</th>
                            <th>Download</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for geodataset in geodatasets %}
                        <tr>
                            <td scope="row"><a href="{% url 'manage:dataset:view_geodataset' geodataset.uuid %}">{{ geodataset.name }}</a></td>
                            <td scope="row"><a href="{% url 'manage:dataset:update_geodataset' geodataset.uuid %}">Update</a></td>
                            <td scope="row"><a href="{% url 'manage:dataset:download_geodataset' geodataset.uuid %}">Download</a></td>
                        </tr>
                        {% endfor %}

                    </tbody>
                  </table></div>
                    {% if is_paginated %}
                        {% include "manage/inc/pagination.html" %}
                    {% endif %}
                </div>
            </div>
            <div class="col-md-3">
                <a href="{% url 'manage:dataset:create_geodataset' %}" class="btn btn-block btn-primary btn-lg btn-card">New Dataset</a>
                <div class="card">
                    <div class="card-header">Filter</div>
                    <div class="card-body">
                        <form action="" method="get">
                            {{ filter.form|crispy }}
                            <input class="btn btn-primary btn-block" type="submit" value="Search" />
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

geodataset/templates/geodataset/geodatasetcategory_confirm_delete.html
{% extends "manage/manage_base.html" %}
{% load sekizai_tags crispy_forms_tags %}

{% block title %}Delete {{ geodatasetcategory.name }}{% endblock title %}

{% block page_content %}
{% add_data "body-class" "election" %}
    <div class="col-md-12">
        <h2>Delete {{ geodatasetcategory.name }}</h2>

            <form role="form" method="POST" action="">
                <p>Are you sure you want to delete <strong>{{ geodatasetcategory.name }}</strong>? You cannot undo this.</p>
            <button type="submit" class="btn btn-danger">Delete</button>
            {% csrf_token %}
            </form>

    </div>
{% endblock %}

geodataset/templates/geodataset/geodatasetcategory_form.html
{% extends "manage/manage_base.html" %}
{% load sekizai_tags crispy_forms_tags %}

{% block title %}{% if geodatasetcategory %}Edit Dataset Category {{ geodatasetcategory }}{% else %}Create Dataset Category{% endif %}{% endblock title %}

{% block content %}
{% add_data "body-class" "targets" %}
{% add_data "body-class" "form-page" %}
<div class="content-wrapper">
    <div class="col-lg-12">
    <div class="card">
        <div class="card-header">{% if geodatasetcategory %}Edit Dataset Category {{ geodatasetcategory }}{% else %}Create Dataset Category{% endif %}</div><div class="card-body">

            <form role="form" method="POST" action="">
            {{ form|crispy }}
            <button type="submit" class="btn btn-block btn-primary">Save</button>
            {% csrf_token %}
            </form>
</div></div></div></div>
    </div>
{% endblock %}

geodataset/templates/geodataset/geodatasetcategory_list.html
{% extends "manage/manage_base.html" %}
{% load sekizai_tags %}

{% block title %}{{ organization.platform_name }} Dataset Categories{% endblock title %}

{% block page_content %}
{% add_data "body-class" "targets" %}
    <div class="col-md-12">
        <h2>{{ organization.platform_name }} Dataset Categories</h2>
        <p><a href="{% url 'manage:dataset:create_geodatasetcategory' %}" class="btn btn-primary">New Dataset Category</a></p>
        <div class="card">
          <!-- Default card contents -->
          <div class="card-header">Existing Dataset Categories</div>
          <!-- Table -->
          <div class="table-responsive-lg">
          <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for geodatasetcategory in geodatasetcategories %}
                <tr>
                    <th scope="row">{{ geodatasetcategory.name }}</th>
                    <th scope="row"><a href="{% url 'manage:dataset:update_geodatasetcategory' geodatasetcategory.uuid %}">Update</a></th>
                    <th scope="row"><a href="{% url 'manage:dataset:delete_geodatasetcategory' geodatasetcategory.uuid %}">Delete</a></th>
                </tr>
                {% endfor %}

            </tbody>
          </table></div>

        </div>

{% if is_paginated %}
{% include "inc/pagination.html" %}
{% endif %}

    </div>
{% endblock %}